################################################################################
# Start Base Url
# https://github.com/uiowa-mgb/personal-site-template/wiki/Base-Url
################################################################################
baseURL: "https://jmiller173.github.io/"
################################################################################
# End Base Url
################################################################################


################################################################################
# Start Title Section
# https://github.com/uiowa-mgb/personal-site-template/wiki/Title-Section
################################################################################
title: "Jacob Miller"
################################################################################
# End Title Section
################################################################################

################################################################################
# Start Site Params
################################################################################
params:

################################################################################
# Start Favicon
# https://github.com/uiowa-mgb/personal-site-template/wiki/Favicon
################################################################################
  favicon: "/icons/favicon.ico"
################################################################################
# End Favicon
################################################################################


################################################################################
# Start Navbar Section
# https://github.com/uiowa-mgb/personal-site-template/wiki/Navbar-Section
################################################################################

  navbar:
    align: ms-auto # No need to change
    disableSearch: false
    stickyNavBar:
      enable : true
      showOnScrollUp : true
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: true
      disableAchievements: false
      disableTalks: false
      disableTeaching: false
      disableContact: true
      main:
        - identifier: Publications
          name: Publications
          title: Publications
          url: /publications
        #Dropdown menu
        - identifier: dropdown
          title: Example dropdown menu
          name: Extras
          children:
            - identifier: Blog
              title: Blog
              name: Blog
              url: /blog
            - identifier: "???"
              title: "???"
              name: "???"
              url: /another_section

################################################################################
# End Navbar Section
################################################################################

################################################################################
# Start Theme Section
# https://github.com/uiowa-mgb/personal-site-template/wiki/Theme-Section
################################################################################
  theme:
    disableThemeToggle: false
    defaultTheme: "light" # dark


  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

################################################################################
# End Theme Section
################################################################################



################################################################################
# Start Hero Section
# https://github.com/uiowa-mgb/personal-site-template/wiki/Hero-Section
################################################################################
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Jacob Miller"
    subtitle: ""
    content: ""
    image: images/Pythagoras.jpeg
    roundImage: true
    button:
      enable: true
      name: "CV"
      url: "/pdf/CV.pdf"
      download: true
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://example.com
        - icon: fab fa-linkedin
          url: https://example.com
      customIcons:
        - icon: images/DNA.png
          url: "https://example.com"


################################################################################
# End Hero Section
################################################################################

################################################################################
# Start About Section
# https://github.com/uiowa-mgb/personal-site-template/wiki/About-Section
################################################################################
  about:
    enable: true
    title: "About Me"
    # image: "/images/Pythagoras.jpeg"
    content: |-
        In dolor dolor, eleifend at leo a, viverra convallis risus. Aliquam eu leo
        diam. Vivamus at urna dignissim, venenatis dolor ut, laoreet elit.
        Lorem ipsum dolor sit amet, consectetur adipiscing elit.
    skills:
      enable: true
      title: "Here are some of my research interests:"
      items:
        - "Triangles"
        - "Circles"
        - "Squares"
        - "Points"
        - "Angles"


################################################################################
# End About Section
################################################################################

################################################################################
# Start education Section
# https://github.com/uiowa-mgb/personal-site-template/wiki/Education-Section
################################################################################
  education:
    enable: true
    # title: "Custom Name"
    index: false
    items:
      - title: "tellus sit amet pulvinar"
        school:
          name: "Hermodamas of Samos"
          url: "https://en.wikipedia.org/w/index.php?title=Hermodamas_of_Samos&action=edit&redlink=1"
        date: "595 BC - 590 BC"
      - title: "Quisque consectetur"
        school:
          name: "Pherecydes of Syros"
          url: "https://en.wikipedia.org/wiki/Pherecydes_of_Syros"
        date: "595 BC - 590 BC"
        GPA: "3.9 out of 5.0"
        content: |-
          In dolor dolor, eleifend at leo a, viverra convallis risus. Aliquam eu leo
          diam. Vivamus at urna dignissim, venenatis dolor ut, laoreet elit.
          Lorem ipsum dolor sit amet, consectetur adipiscing elit.
        featuredLink:
          enable: true
          name: "My academic record"
          url: "https://example.com"



################################################################################
# End education Section
################################################################################

################################################################################
# Start experience Section
# https://github.com/uiowa-mgb/personal-site-template/wiki/Experience-Section
################################################################################
  experience:
    enable: true
    # title: "Custom Name"
    items:
      - job: "Teacher"
        company: "dui eros sagittis ligula"
        companyUrl: "https://example.com"
        date: "February 499BC - February 495BC"
        featuredLink:
          enable: false
          name: "View the project"
          url: "https://example.com"
        content: "Duis aliquam at leo in hendrerit. Sed id posuere magna. "


      - job: "Teacher"
        company: "leo in hendrerit"
        companyUrl: "https://example.com"
        date: "February 500BC - February 499BC"
        content: "Duis aliquam at leo in hendrerit. Sed id posuere magna. "


################################################################################
# End experience Section
################################################################################


################################################################################
# Start talks Section
# https://github.com/uiowa-mgb/personal-site-template/wiki/Talks-Section
################################################################################
  talks:
    enable: true
    # title: "Custom Name"
    index: false
    items:
      - title: "A talk about triangles"
        info:
          name: "Hermodamas of Samos Conference of champions"
          url: "https://en.wikipedia.org/w/index.php?title=Hermodamas_of_Samos&action=edit&redlink=1"
        date: "590 495BC"
      - title: "A talk about Circles"
        info:
          name: "Hermodamas of Samos Conference of champions"
          url: "https://en.wikipedia.org/w/index.php?title=Hermodamas_of_Samos&action=edit&redlink=1"
        date: "591 BC"
        content: |-
            - Lorem ipsum dolor sit amet consectetur adipisicing elit.
            - Tempora esse, eaque delectus nulla quo doloribus itaque expedita alias natus optio totam maxime nihil excepturi velit a animi laborum hic similique.
        featuredLink:
          enable: true
          name: "Slides"
          url: "https://example.com"


################################################################################
# End talks Section
################################################################################

################################################################################
# Start teaching Section
# https://github.com/uiowa-mgb/personal-site-template/wiki/Teaching-Section
################################################################################
  teaching:
    enable: true
    # title: "Custom Name"
    index: false
    items:
      - title: "Triangles 101"
        info:
          name: "University technical college"
          url: "https://en.wikipedia.org/w/index.php?title=Hermodamas_of_Samos&action=edit&redlink=1"
        date: "Fall 590 BC"
      - title: "Circles 101"
        info:
          name: "University technical college"
          url: "https://en.wikipedia.org/w/index.php?title=Hermodamas_of_Samos&action=edit&redlink=1"
        date: "Spring 591 BC"
        content: |-
            - Lorem ipsum dolor sit amet consectetur adipisicing elit.
            - Tempora esse, eaque delectus nulla quo doloribus itaque expedita alias natus optio totam maxime nihil excepturi velit a animi laborum hic similique.
        featuredLink:
          enable: true
          name: "Syllabus"
          url: "https://example.com"


################################################################################
# End teaching Section
################################################################################

################################################################################
# Start achievements Section
# https://github.com/uiowa-mgb/personal-site-template/wiki/Achievements-Section
################################################################################
  achievements:
    enable: true
    title: "Awards"
    items:
      - title: Some fellowship
        content: |-
           Donec viverra ultricies aliquam. Praesent at bibendum mi, quis euismod dolor. Vivamus vel diam quis turpis gravida commodo non vitae lacus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nunc commodo justo ipsum, eget consequat nibh semper a. Etiam fermentum lectus sapien
      - title: Some other fellowship
        content: Praesent at bibendum mi, quis euismod dolor.
        image: /images/Pythagoras.jpeg
        url: https://example.com


################################################################################
# End achievements Section
################################################################################

################################################################################
# Start projects Section
# https://github.com/uiowa-mgb/personal-site-template/wiki/Projects-Section
################################################################################
  projects:
    enable: false
    # title: "Custom Name"
    items:
      - title: Hugo Profile
        content: A highly customizable and mobile first Hugo template for personal portfolio and blog.
        image: /images/projects/profile.png
        featured:
          name: Demo
          link: https://hugo-profile.netlify.app
        badges:
          - "Hugo"
          - "Bootstrap"
          - "Javascript"
        links:
          - icon: fa fa-envelope
            url: mailto:?subject=Hugo%20Profile%20Template&body=Check%20it%20out:%20https%3a%2f%2fhugo-profile.netlify.app%2fblog%2fmarkdown-syntax%2f
          - icon: fab fa-github
            url: https://github.com/gurusabarish/hugo-profile
          - icon: fab fa-twitter
            url: https://twitter.com/intent/tweet?text=Check+it+out:&url=https%3A%2F%2Fgithub.com%2Fgurusabarish%2Fhugo-profile


################################################################################
# End projects Section
################################################################################

################################################################################
# Start contact Section
# https://github.com/uiowa-mgb/personal-site-template/wiki/Contact-Section
################################################################################
  contact:
    enable: true
    # title: "Custom Name"
    # content: My inbox is always open. Whether you have a question or just want to say hi, I'll try my best to get back to you!
    email: Pythagoras@mathgradboard.com
    btnName: Mail me


################################################################################
# End contact Section
################################################################################

################################################################################
# No need to change anything from here
################################################################################

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"

  useBootstrapCDN: false
  mathjax: true
  animate: true
  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left
  #customScripts: -| # You can add custom scripts which will be added before </body> tag
  #  <script type="text/javascript"><!-- any script here --></script>

languageCode: "en-us"
theme: hugo-profile
outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"
Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

################################################################################
# to here
################################################################################

################################################################################
# End Site Params
################################################################################