languageCode = "en-us"
theme = "hugo-resume"


# ==============================================================================
# The url for the website
# ==============================================================================
baseURL = "https://personal.mathgradboard.com/"

# ==============================================================================
# Personal info section (can leave blank by leaving "")
# ==============================================================================

title = "Pythagoras of Samos"

[params]
address = "Metapontum Village, Italy"
email = "Pythagoras@mathgradboard.com"
favicon = "/icon/favicon.ico"
firstName = "Pythagoras"
lastName = "of Samos"
phone = "1-555-555-5555"

# ==============================================================================
# Personal photo section. Replace with name of new file
# ==============================================================================
profileImage = "images/Pythagoras.jpeg"

# ==============================================================================
# Enable disable page sections
# ==============================================================================
showEducation = true
showPublications = true
showConferences = true
showTeaching = true
showBlog = true
showService = true
showAwards = true

showExperience = false
showProjects = false
showSkills = false
showQr = false
showCertifications = false
showOpenSource = false

# ==============================================================================
# Add/remove social media accounts
# ==============================================================================
[[params.handles]]
link = "https://www.linkedin.com/"
name = "LinkedIn"

[[params.handles]]
link = "https://github.com/uiowa-mgb"
name = "GitHub"

# Add as many as you like. So long as the name is found on this list
# https://fontawesome.com/v4/icons/#brand
# it should render a logo. For example:

# [[params.handles]]
# link = "https://mathoverflow.net/users/"
# name = "Stack-Overflow"

# [[params.handles]]
# link = "https://www.pinterest.com/"
# name = "pinterest"

# [[params.handles]]
# link = "https://www.youtube.com/"
# name = "youtube"

# [[params.handles]]
# link = "https://www.instagram.com/"
# name = "instagram"


# ==============================================================================
# No need to change anything below here
# ==============================================================================


PygmentsCodeFences = true
PygmentsCodeFencesGuessSyntax = true
PygmentsStyle = "monokai"
enableGitInfo = false

[outputs]
home = ["HTML", "JSON"]

[taxonomies]
tag = "tags"
